Cats/Models/Cat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cats.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cats.Models
{
    public class Cat
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; } // Порода
        public int Price { get; set; }
    }
   
}

Cats/Models/CatContexts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace Cats.Models
{
    public class CatContext : DbContext
    {
        
        public DbSet<Cat> Cats { get; set; }

        public DbSet<Dog> Dogs { get; set; }
        public CatContext(DbContextOptions<CatContext> options)
        : base(options)
        {
            Database.EnsureCreated();
        }

    }
}

Cats/Models/Dog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cats.Models
{
    public class Dog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; } // Порода
        public int Price { get; set; }

    }
}

Cats/Models/SampleData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cats.Models;

namespace Cats.Models
{
    public static class SampleData
    {
        public static void Initialize(CatContext context)
        {
            if (!context.Cats.Any())
            {
                context.Cats.AddRange(
                    new Cat
                    {
                        Name = "Барсик",
                        Breed = "Британец",
                        Price = 600
                    },
                    new Cat
                    {
                        Name = "Мурзик",
                        Breed = "Вислоухий",
                        Price = 550
                    },
                    new Cat
                    {
                        Name = "Пушистик",
                        Breed = "Обыкновенный",
                        Price = 500
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

Cats/Controllers/DogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cats.Models;
using Microsoft.EntityFrameworkCore;

namespace Dogs.Controllers
{
    public class DogController : Controller
    {
       CatContext db;
        public DogController(CatContext context)
        {
            db = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await db.Dogs.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Dog dog)
        {

            db.Dogs.Add(dog);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Dog dog = await db.Dogs.FirstOrDefaultAsync(p => p.Id == id);
                if (dog != null)
                    return View(dog);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Dog dog)
        {
            db.Dogs.Update(dog);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Dog dog = await db.Dogs.FirstOrDefaultAsync(p => p.Id == id);
                if (dog != null)
                    db.Dogs.Remove(dog);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return NotFound();
        }



        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Dog dog = await db.Dogs.FirstOrDefaultAsync(p => p.Id == id);
                if (dog != null)
                    return View(dog);
            }
            return NotFound();
        }
    }
}

Cats/Controllers/HomeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Cats.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;




namespace Cats.Controllers
{
    public class HomeController : Controller
    {
        CatContext db;
        public HomeController(CatContext context)
        {
            db = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await db.Cats.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Cat cat)
        {
          
            db.Cats.Add(cat);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Cat cat = await db.Cats.FirstOrDefaultAsync(p => p.Id == id);
                if (cat != null)
                    return View(cat);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Cat cat)
        {
            db.Cats.Update(cat);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Cat cat = await db.Cats.FirstOrDefaultAsync(p => p.Id == id);
                if (cat != null)
                    return View(cat);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Cat cat = await db.Cats.FirstOrDefaultAsync(p => p.Id == id);
                if (cat != null)
                {
                    db.Cats.Remove(cat);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Cat cat = await db.Cats.FirstOrDefaultAsync(p => p.Id == id);
                if (cat != null)
                    return View(cat);
            }
            return NotFound();
        }
    }
}

Cats/Views/Dogs/Create.cshtml
@model Cats.Models.Dog
@{
    ViewBag.Title = "Добавление собакена";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню собакена</title>
</head>
<body>
    <form asp-action="create" asp-controller="home">
        <div class="form-group">

            <label asp-for="Name" class="control-label">Кличка</label>
            <input type="text" asp-for="Name" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Breed" class="control-label">Порода</label>
            <input type="text" asp-for="Breed" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Price" class="control-label">Цена</label>

            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Отправить" class="btn btn-default" />

        </div>
    </form>
</body>
</html>

Cats/Views/Dogs/Details.cshtml
@model Cats.Models.Dog
@{
    ViewBag.Title = "Информация о собакене";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню собакене</title>
</head>
<body>

    <h2>Котик @Model.Name</h2>
    <div>
        <dl class="dl-horizontal">
            <dt>Идентификатор</dt>
            <dd>@Model.Id</dd>

            <dt>Порода</dt>
            <dd>@Model.Breed</dd>

            <dt>Кличка</dt>
            <dd>@Model.Name</dd>

            <dt>Цена</dt>
            <dd>@Model.Price</dd>
        </dl>
    </div>
</body>
</html>

Cats/Views/Dogs/Edit.cshtml
@model Cats.Models.Dog
@{
    ViewBag.Title = "Редактирование собакена";
}
<!DOCTYPE html>
<html>
<head>
    <title>Меню собакенов</title>
</head>
<body>
    <form asp-action="Edit" asp-controller="home">
        <div class="form-group">

            <label asp-for="Name" class="control-label">Кличка</label>
            <input type="text" asp-for="Name" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Breed" class="control-label">Порода</label>
            <input type="text" asp-for="Breed" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Price" class="control-label">Цена</label>

            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Отправить" class="btn btn-default" />
        </div>
    </form>
</body>
</html>

Cats/Views/Dogs/Index.cshtml
@model IEnumerable<Dog>
@{

    ViewData["Title"] = "Каталог котиков";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню собакенов</title>

</head>
<body>
    <h3> Выбор собакена</h3>
    <table class="table-condensed">
        <tr>
            <td>Кличка</td>
            <td>Порода</td>
            <td>Цена</td>
            <td></td>
        </tr>

        @foreach (var dog in Model)
        {
            <tr>
                <td>@dog.Name</td>
                <td>@dog.Breed</td>
                <td>@dog.Price</td>

                <td><a asp-action="Edit" asp-controller="Dog" asp-route-id="@dog.Id">Редактировать</a></td>

                <td><a asp-action="Delete" asp-controller="Dog" asp-route-id="@dog.Id">Удалить</a></td>

                <td><a asp-action="Details" asp-controller="Dog" asp-route-id="@dog.Id">Информация</a></td>

            </tr>
        }

    </table>
    <style>
        p {
            margin-top: 10px;
        }
    </style>
    <p><hr /></p>
    <a href="~/Dog/Dogs/Create" class="Create">Добавить собакена</a>




</body>
</html>

Cats/Views/Home/Create.cshtml
@model Cats.Models.Cat
@{
    ViewBag.Title = "Добавление котиков";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню котиковв</title>
</head>
<body>
    <form asp-action="create" asp-controller="home">
        <div class="form-group">

            <label asp-for="Name" class="control-label">Кличка</label>
            <input type="text" asp-for="Name" class="form-control" />
   
        </div>
        <div class="form-group">

            <label asp-for="Breed" class="control-label">Порода</label>
            <input type="text" asp-for="Breed" class="form-control" />
          
        </div>
        <div class="form-group">

            <label asp-for="Price" class="control-label">Цена</label>
           
            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Отправить" class="btn btn-default" />
            
        </div>
    </form>
</body>
</html>

Cats/Views/Home/Details.cshtml
@model Cats.Models.Cat
@{
    ViewBag.Title = "Информация о котиках";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню котиковв</title>
</head>
<body>

    <h2>Котик @Model.Name</h2>
    <div>
        <dl class="dl-horizontal">
            <dt>Идентификатор</dt>
            <dd>@Model.Id</dd>

            <dt>Порода</dt>
            <dd>@Model.Breed</dd>

            <dt>Кличка</dt>
            <dd>@Model.Name</dd>

            <dt>Цена</dt>
            <dd>@Model.Price</dd>
        </dl>
    </div>
</body>
</html>

Cats/Views/Home/Edit.cshtml
@model Cats.Models.Cat
@{
    ViewBag.Title = "Редактирование котиков";
}
<!DOCTYPE html>
<html>
<head>
    <title>Меню котиковв</title>
</head>
<body>
    <form asp-action="Edit" asp-controller="home">
        <div class="form-group">

            <label asp-for="Name" class="control-label">Кличка</label>
            <input type="text" asp-for="Name" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Breed" class="control-label">Порода</label>
            <input type="text" asp-for="Breed" class="form-control" />

        </div>
        <div class="form-group">

            <label asp-for="Price" class="control-label">Цена</label>

            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Отправить" class="btn btn-default" />
        </div>
    </form>
</body>
</html>

Cats/Views/Home/Index.cshtml
@model IEnumerable<Cat>
@{
     
   ViewData["Title"] = "Каталог котиков";
}
<!DOCTYPE html>

<html>
<head>
    <title>Меню котиковв</title>

</head>
<body>
    <h3> Выбор Котиков</h3>
    <table class="table-condensed">
        <tr>
            <td>Кличка</td>
            <td>Порода</td>
            <td>Цена</td>
            <td></td>
        </tr>

        @foreach (var cat in Model)
        {
    <tr>
        <td>@cat.Name</td>
        <td>@cat.Breed</td>
        <td>@cat.Price</td>

        <td><a asp-action="Edit" asp-controller="Home" asp-route-id="@cat.Id">Редактировать</a></td>

        <td><a asp-action="Delete" asp-controller="Home" asp-route-id="@cat.Id" >Удалить</a></td>
        
        <td><a asp-action="Details" asp-controller="Home" asp-route-id="@cat.Id">Информация</a></td>

    </tr>
        }

    </table>
    <style>
        p {
            margin-top: 10px;
        }
    </style>
    <p><hr /></p>
         <a href="~/Home/Create" class="Create">Добавить котика</a>
        
       


</body>
</html>

Cats/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <style>
        a.Create {
            color: #fff;
            user-select: none; /* Убираем текстовое выделение */
            text-decoration: none; /* Убираем подчеркивание */
            outline: none; /* Убираем контур вокруг ссылки */
            background-color: #fa8e47; /* Цвет фона */
            padding: 1em 2em; /* Отступ от текста до рамки */
        }

            a.Create:active {
                background-color: #ee6206; /* Цвет кнопки при нажатии */
            }

            a.Create:hover {
                background-color: #f97f2e; /* Цвет кнопки при наведении курсора */
            }
    </style>
    <style>  
    h3 {
    font-family: 'Times New Roman', Times, serif; /* Шрифт с засечками */
    font-style: italic; /* Курсивное начертание */
       }
    </style>
</head>
<body>
    <!--меню-->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div>
                <ul class="nav navbar-nav">
                    <li><a href="~/Home/index" class="navbar-brand">Главная</a></li>
                    <li><a href="~/Dog/index" class="table-condensed">Собакены</a></li>
                </ul>
            </div>
        </div>
    </nav>
   

    <!--основной контент-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© 2020 - CatStore</p>
        </footer>
    </div>
</body>
</html>